  server:
    port: 8080
  spring:
    application:
      name: config-server
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
    cloud:
      config:
        server:
          git:
            uri: https://github.com/wangxun-git/MyGit.git/
            username: 945097967@qq.com
            password: wx971013
            search-paths: /
  management:
    endpoints:
      web:
        exposure:
          include: bus,bus-refresh

  eureka:
    client:
      serviceUrl:
        defaultZone: http://wang:1234@localhost:8761/eureka/
    instance: #采用IP注册
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}